#!/bin/env bash

# deps: bspwm, texlive, emacs, pdflatex, catdvi

cd /tmp

bspc rule -a Emacs --one-shot state=floating

> /tmp/latex-copy.tex
# emacsclient -c -a 'emacs' /tmp/latex-copy.tex
emacsclient -nw -c -a 'emacs' /tmp/latex-copy.tex

echo "%&latex
\documentclass[border=0.2cm]{standalone}
\usepackage{amsmath, amsthm, amssymb, graphicx, multicol, array}
\newcommand{\st}{\text{ s.t. }}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\Q}{\mathbb{Q}}
\renewcommand{\qedsymbol}{(\blacksquare)}
\renewcommand*{\proofname}{\underline{Pf}:}
\pagestyle{empty}
\title{TITLE}
\author{Hisbaan Noorani}
\date{DATE}
\begin{document}
\input{/tmp/latex-copy.tex}
\end{document}" > /tmp/latex-pic.tex
# might not need the whole big thing. Just the small latex file.
# use pandoc to convert to txt (or just use the small latex file directly)
# run it though a little replace thing where it interprets the plain text
# (or use the one that you saw on github if you can find it again)

pdflatex -shell -interaction nonstopmode /tmp/latex-pic.tex
[ -f /tmp/latex-pic.pdf ] && convert -density /tmp/latex-pic.pdf /tmp/latex-pic.png
[ -f /tmp/latex-pic.png ] && xclip -sellection clipboard -t image/png -i /tmp/latex-pic.png
